#ifndef OPTIONS_H
#define OPTIONS_H

#define TESTS_ENABLED 1

/* BSOD */
#define ENABLE_TEST_DIV_ZERO 0
#define ENABLE_TEST_UD 0
#define ENABLE_TEST_NULLPTR 0
#define ENABLE_TEST_USPACE_PTR 0
#define ENABLE_TEST_VIDMEM_EDGE 0

#define ENABLE_TEST_IDT 1
#define ENABLE_TEST_PAGING 1
#define ENABLE_TEST_KEYPRESS 1
#define ENABLE_TEST_TERMINAL 1
#define ENABLE_TEST_SHELL 1
#define ENABLE_TEST_LS 1
#define ENABLE_TEST_CAT_FRAME0 1
#define ENABLE_TEST_CAT_VLTWLN 1
#define ENABLE_TEST_CAT_HELLO 1
#define ENABLE_TEST_RTC_WRITE 1
#define ENABLE_TEST_RTC_READ 1
#define ENABLE_TEST_FS 1

/* RTC demonstrations */
#define RTC_RANDOM_TEXT_DEMO 0 /* CP1 */
#define ENABLE_TEST_RTC_DEMO 0 /* CP2 */

#endif
